# Generated by Django 3.2.25 on 2025-02-16 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothImage', models.ImageField(upload_to='clothes/')),
                ('type', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Dress', 'Dress')], max_length=10)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('isFavorite', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothSubType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothClothSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.cloth')),
                ('clothSubType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.clothsubtype')),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='cloth_subtypes',
            field=models.ManyToManyField(related_name='clothes', through='clothing.ClothClothSubType', to='clothing.ClothSubType'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
