# Generated by Django 3.2.25 on 2025-02-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Onepiece', 'Onepiece')], max_length=10),
        ),
    ]
