# Generated by Django 3.2.25 on 2025-02-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_image', models.ImageField(upload_to='body_images/')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('chest_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_width', models.IntegerField(blank=True, null=True)),
                ('arm_length', models.IntegerField(blank=True, null=True)),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTryOnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('body_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tryon_images', to='vtryon.bodyimage')),
                ('bottom_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_virtual_tryon_images', to='clothing.cloth')),
                ('dress_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dress_virtual_tryon_images', to='clothing.cloth')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tryon_images', to=settings.AUTH_USER_MODEL)),
                ('top_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_virtual_tryon_images', to='clothing.cloth')),
            ],
        ),
    ]
